# Generated by Django 4.2.7 on 2023-11-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_hashtag_review_equipment_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='post.category'),
        ),
    ]
